baseURL = "https://iitmod.github.io/"
#CanonifyURLs=true

languageCode = "en-us"
theme = "ramium"

title = "IITMOD"
disqusShortname = "disqus-code"
googleAnalytics = "analytics-code"
pluralizeListTitles = false
enableemoji = false

[params]
    description = "A description for the meta tag of the site"
    googleSearch = "google-search-code"
    showDate = false # make false if dont want to show date for evergeen articles
    math = false # best to enable this in the front matter of a page
    githubLink = "github.com/iitmod/"

    tagsInHome =0     # set zero to not show in home page
    sectionsInHome =0   # set zero to not show in home page
    paginatePostsPerPage = 5
    paginateTagsPerPage = 6

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
    unsafe = true

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "Sections"
        weight = 2
            [[menu.main]]
                parent = "blog"
                name = "Foundtion"
                url = "/"
                weight = 1
            [[menu.main]]
                parent = "blog"
                name = "Diploma"
                url = "/"
                weight = 2
            [[menu.main]]
                parent = "blog"
                name = "Degree"
                url = "/"
                weight = 3
    
    [[menu.main]]
        name = "About us"
        url = "/authorr/"
        weight = 3
